import { ExerciseDefinition } from "./types";

export const EXERCISES: ExerciseDefinition[] = [
  // CHEST (17)
  { id: "chest-1", name: "Bench Press (Barbell)", muscle: "Chest", muscle_groups: ["Chest", "Triceps", "Shoulders"], category: "Chest", equipment: "Barbell", equipment_list: ["Barbell", "Bench"] },
  { id: "chest-2", name: "Bench Press – Close Grip (Barbell)", muscle: "Chest", muscle_groups: ["Chest", "Triceps"], category: "Chest", equipment: "Barbell", equipment_list: ["Barbell", "Bench"] },
  { id: "chest-3", name: "Bench Press – Wide Grip (Barbell)", muscle: "Chest", muscle_groups: ["Chest", "Shoulders"], category: "Chest", equipment: "Barbell", equipment_list: ["Barbell", "Bench"] },
  { id: "chest-4", name: "Bench Press (Dumbbell)", muscle: "Chest", muscle_groups: ["Chest", "Triceps", "Shoulders"], category: "Chest", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },
  { id: "chest-5", name: "Decline Bench Press (Dumbbell)", muscle: "Chest", muscle_groups: ["Lower Chest", "Triceps"], category: "Chest", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },
  { id: "chest-6", name: "Floor Press (Barbell)", muscle: "Chest", muscle_groups: ["Chest", "Triceps"], category: "Chest", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "chest-7", name: "Incline Push Ups", muscle: "Chest", muscle_groups: ["Lower Chest", "Triceps"], category: "Chest", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "chest-8", name: "Push Up (Weighted)", muscle: "Chest", muscle_groups: ["Chest", "Triceps", "Shoulders"], category: "Chest", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Weight Plate"] },
  { id: "chest-9", name: "Chest Dip", muscle: "Chest", muscle_groups: ["Lower Chest", "Triceps"], category: "Chest", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Dip Station"] },
  { id: "chest-10", name: "Chest Dip (Weighted)", muscle: "Chest", muscle_groups: ["Lower Chest", "Triceps"], category: "Chest", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Dip Station", "Dumbbell"] },
  { id: "chest-11", name: "Pullover (Dumbbell)", muscle: "Chest", muscle_groups: ["Chest", "Lats"], category: "Chest", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },
  { id: "chest-12", name: "Around The Worlds (Dumbbell)", muscle: "Chest", muscle_groups: ["Chest", "Shoulders"], category: "Chest", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },
  { id: "chest-13", name: "Plate Press", muscle: "Chest", muscle_groups: ["Chest"], category: "Chest", equipment: "Weight Plate", equipment_list: ["Weight Plate"] },
  { id: "chest-14", name: "Cable Chest Fly", muscle: "Chest", muscle_groups: ["Chest"], category: "Chest", equipment: "Machine", equipment_list: ["Machine", "Cables"] },
  { id: "chest-15", name: "Pec Deck Fly", muscle: "Chest", muscle_groups: ["Chest"], category: "Chest", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "chest-16", name: "Incline Bench Press (Dumbbell)", muscle: "Chest", muscle_groups: ["Upper Chest", "Shoulders", "Triceps"], category: "Chest", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },
  { id: "chest-17", name: "Incline Bench Press (Barbell)", muscle: "Chest", muscle_groups: ["Upper Chest", "Shoulders", "Triceps"], category: "Chest", equipment: "Barbell", equipment_list: ["Barbell", "Bench"] },

  // SHOULDERS (12)
  { id: "shoulders-1", name: "Arnold Press (Dumbbell)", muscle: "Shoulders", muscle_groups: ["Shoulders", "Triceps"], category: "Shoulders", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "shoulders-2", name: "Face Pull", muscle: "Shoulders", muscle_groups: ["Rear Delts", "Upper Back"], category: "Shoulders", equipment: "Machine", equipment_list: ["Machine", "Cables", "Rope"] },
  { id: "shoulders-3", name: "Handstand Push Up", muscle: "Shoulders", muscle_groups: ["Shoulders", "Triceps"], category: "Shoulders", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "shoulders-4", name: "Bent Over Fly (Dumbbell)", muscle: "Shoulders", muscle_groups: ["Rear Delts", "Upper Back"], category: "Shoulders", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "shoulders-5", name: "Seated Overhead Press (Barbell)", muscle: "Shoulders", muscle_groups: ["Shoulders", "Triceps"], category: "Shoulders", equipment: "Barbell", equipment_list: ["Barbell", "Bench"] },
  { id: "shoulders-6", name: "Plate Front Raise", muscle: "Shoulders", muscle_groups: ["Front Delts"], category: "Shoulders", equipment: "Weight Plate", equipment_list: ["Weight Plate"] },
  { id: "shoulders-7", name: "Standing Military Press (Barbell)", muscle: "Shoulders", muscle_groups: ["Shoulders", "Triceps", "Core"], category: "Shoulders", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "shoulders-8", name: "Push Press", muscle: "Shoulders", muscle_groups: ["Shoulders", "Triceps", "Legs"], category: "Shoulders", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "shoulders-9", name: "Lateral Raise (Dumbbell)", muscle: "Shoulders", muscle_groups: ["Side Delts"], category: "Shoulders", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "shoulders-10", name: "Front Raise (Dumbbell)", muscle: "Shoulders", muscle_groups: ["Front Delts"], category: "Shoulders", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "shoulders-11", name: "Seated Dumbbell Press", muscle: "Shoulders", muscle_groups: ["Shoulders", "Triceps"], category: "Shoulders", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },
  { id: "shoulders-12", name: "Lateral Raise (Machine / Cable)", muscle: "Shoulders", muscle_groups: ["Side Delts"], category: "Shoulders", equipment: "Machine", equipment_list: ["Machine"] },

  // BICEPS (11)
  { id: "biceps-1", name: "Bicep Curl (Dumbbell)", muscle: "Biceps", muscle_groups: ["Biceps", "Forearms"], category: "Biceps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "biceps-2", name: "Bicep Curl (Barbell)", muscle: "Biceps", muscle_groups: ["Biceps", "Forearms"], category: "Biceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "biceps-3", name: "Hammer Curl (Dumbbell)", muscle: "Biceps", muscle_groups: ["Biceps", "Forearms"], category: "Biceps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "biceps-4", name: "Concentration Curl", muscle: "Biceps", muscle_groups: ["Biceps"], category: "Biceps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "biceps-5", name: "Reverse Curl (Barbell)", muscle: "Biceps", muscle_groups: ["Biceps", "Forearms"], category: "Biceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "biceps-6", name: "Plate Curls", muscle: "Biceps", muscle_groups: ["Biceps", "Forearms"], category: "Biceps", equipment: "Weight Plate", equipment_list: ["Weight Plate"] },
  { id: "biceps-7", name: "Behind the Back Wrist Curl (Barbell)", muscle: "Biceps", muscle_groups: ["Forearms"], category: "Biceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "biceps-8", name: "EZ Bar Curl", muscle: "Biceps", muscle_groups: ["Biceps", "Forearms"], category: "Biceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "biceps-9", name: "Cable Bicep Curl", muscle: "Biceps", muscle_groups: ["Biceps", "Forearms"], category: "Biceps", equipment: "Machine", equipment_list: ["Machine", "Cables"] },
  { id: "biceps-10", name: "Zottman Curl", muscle: "Biceps", muscle_groups: ["Biceps", "Forearms"], category: "Biceps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "biceps-11", name: "Incline Curl (Dumbbell)", muscle: "Biceps", muscle_groups: ["Biceps"], category: "Biceps", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },

  // TRICEPS (13)
  { id: "triceps-1", name: "Bench Press – Close Grip (Barbell)", muscle: "Triceps", muscle_groups: ["Triceps", "Chest"], category: "Triceps", equipment: "Barbell", equipment_list: ["Barbell", "Bench"] },
  { id: "triceps-2", name: "Triceps Dip (Weighted)", muscle: "Triceps", muscle_groups: ["Triceps", "Chest", "Shoulders"], category: "Triceps", equipment: "Machine", equipment_list: ["Machine", "Dip Station"] },
  { id: "triceps-3", name: "One-Arm Tricep Extension (Dumbbell)", muscle: "Triceps", muscle_groups: ["Triceps"], category: "Triceps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "triceps-4", name: "Triceps Extension (Barbell)", muscle: "Triceps", muscle_groups: ["Triceps"], category: "Triceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "triceps-5", name: "Skullcrusher (Barbell)", muscle: "Triceps", muscle_groups: ["Triceps"], category: "Triceps", equipment: "Barbell", equipment_list: ["Barbell", "Bench"] },
  { id: "triceps-6", name: "Dumbbell Skullcrusher", muscle: "Triceps", muscle_groups: ["Triceps"], category: "Triceps", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },
  { id: "triceps-7", name: "Diamond Push Up", muscle: "Triceps", muscle_groups: ["Triceps", "Chest"], category: "Triceps", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "triceps-8", name: "Ring Dips", muscle: "Triceps", muscle_groups: ["Triceps", "Chest", "Shoulders"], category: "Triceps", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Rings"] },
  { id: "triceps-9", name: "Triceps Extension (Suspension)", muscle: "Triceps", muscle_groups: ["Triceps"], category: "Triceps", equipment: "Suspension Band", equipment_list: ["Suspension Band"] },
  { id: "triceps-10", name: "Triceps Rope Pushdown (Cable)", muscle: "Triceps", muscle_groups: ["Triceps"], category: "Triceps", equipment: "Machine", equipment_list: ["Machine", "Cables", "Rope"] },
  { id: "triceps-11", name: "Tricep Dips (Bodyweight)", muscle: "Triceps", muscle_groups: ["Triceps", "Chest", "Shoulders"], category: "Triceps", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Bench"] },
  { id: "triceps-12", name: "Cable Overhead Tricep Extension", muscle: "Triceps", muscle_groups: ["Triceps"], category: "Triceps", equipment: "Machine", equipment_list: ["Machine", "Cables"] },
  { id: "triceps-13", name: "Triceps Kickback (Dumbbell)", muscle: "Triceps", muscle_groups: ["Triceps"], category: "Triceps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },

  // UPPER BACK (12)
  { id: "upper-back-1", name: "Chest-Supported Incline Row (Dumbbell)", muscle: "Upper Back", muscle_groups: ["Upper Back", "Biceps", "Rear Delts"], category: "Upper Back", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },
  { id: "upper-back-2", name: "Meadows Row", muscle: "Upper Back", muscle_groups: ["Upper Back", "Lats"], category: "Upper Back", equipment: "Barbell", equipment_list: ["Barbell", "Landmine"] },
  { id: "upper-back-3", name: "Pendlay Row", muscle: "Upper Back", muscle_groups: ["Upper Back", "Lats", "Core"], category: "Upper Back", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "upper-back-4", name: "Bent Over Fly (Dumbbell)", muscle: "Upper Back", muscle_groups: ["Rear Delts", "Upper Back"], category: "Upper Back", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "upper-back-5", name: "Scapular Pull-Ups", muscle: "Upper Back", muscle_groups: ["Upper Back", "Lats"], category: "Upper Back", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar"] },
  { id: "upper-back-6", name: "Dead Hang", muscle: "Upper Back", muscle_groups: ["Forearms", "Upper Back"], category: "Upper Back", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar"] },
  { id: "upper-back-7", name: "Renegade Row", muscle: "Upper Back", muscle_groups: ["Upper Back", "Core", "Shoulders"], category: "Upper Back", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "upper-back-8", name: "T-Bar Row", muscle: "Upper Back", muscle_groups: ["Upper Back", "Lats", "Biceps"], category: "Upper Back", equipment: "Barbell", equipment_list: ["Barbell", "Machine"] },
  { id: "upper-back-9", name: "Inverted Row", muscle: "Upper Back", muscle_groups: ["Upper Back", "Lats", "Biceps"], category: "Upper Back", equipment: "Machine", equipment_list: ["Machine", "Rings", "Bar"] },
  { id: "upper-back-10", name: "Bent Over Row (Barbell)", muscle: "Upper Back", muscle_groups: ["Upper Back", "Lats", "Biceps"], category: "Upper Back", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "upper-back-11", name: "Single-Arm Row (Dumbbell)", muscle: "Upper Back", muscle_groups: ["Upper Back", "Lats", "Biceps"], category: "Upper Back", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "upper-back-12", name: "Seated Cable Row", muscle: "Upper Back", muscle_groups: ["Upper Back", "Lats", "Biceps"], category: "Upper Back", equipment: "Machine", equipment_list: ["Machine", "Cables"] },

  // LATS (9)
  { id: "lats-1", name: "Sternum Pull Up (Gironda)", muscle: "Lats", muscle_groups: ["Lats", "Upper Back", "Biceps"], category: "Lats", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar"] },
  { id: "lats-2", name: "Lat Pulldown (Band)", muscle: "Lats", muscle_groups: ["Lats", "Biceps"], category: "Lats", equipment: "Machine", equipment_list: ["Resistance Band"] },
  { id: "lats-3", name: "Pull Up", muscle: "Lats", muscle_groups: ["Lats", "Upper Back", "Biceps"], category: "Lats", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar"] },
  { id: "lats-4", name: "Kipping Pull Up", muscle: "Lats", muscle_groups: ["Lats", "Full Body"], category: "Lats", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar"] },
  { id: "lats-5", name: "Lat Pulldown (Cable)", muscle: "Lats", muscle_groups: ["Lats", "Biceps"], category: "Lats", equipment: "Machine", equipment_list: ["Machine", "Cables"] },
  { id: "lats-6", name: "Lat Pulldown (Machine)", muscle: "Lats", muscle_groups: ["Lats", "Biceps"], category: "Lats", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "lats-7", name: "Single Arm Lat Pulldown", muscle: "Lats", muscle_groups: ["Lats", "Biceps"], category: "Lats", equipment: "Machine", equipment_list: ["Machine", "Cables"] },
  { id: "lats-8", name: "Chin Up", muscle: "Lats", muscle_groups: ["Lats", "Biceps", "Chest"], category: "Lats", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar"] },
  { id: "lats-9", name: "Weighted Pull Up", muscle: "Lats", muscle_groups: ["Lats", "Upper Back", "Biceps"], category: "Lats", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar", "Dumbbell"] },

  // LOWER BACK (5)
  { id: "lower-back-1", name: "Superman", muscle: "Lower Back", muscle_groups: ["Lower Back", "Glutes"], category: "Lower Back", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "lower-back-2", name: "Rack Pull", muscle: "Lower Back", muscle_groups: ["Lower Back", "Traps", "Forearms"], category: "Lower Back", equipment: "Barbell", equipment_list: ["Barbell", "Power Rack"] },
  { id: "lower-back-3", name: "Deadlift (Barbell)", muscle: "Lower Back", muscle_groups: ["Lower Back", "Hamstrings", "Glutes", "Forearms"], category: "Lower Back", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "lower-back-4", name: "Romanian Deadlift (Barbell)", muscle: "Lower Back", muscle_groups: ["Hamstrings", "Glutes", "Lower Back"], category: "Lower Back", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "lower-back-5", name: "Hyperextension / Back Extension", muscle: "Lower Back", muscle_groups: ["Lower Back", "Hamstrings", "Glutes"], category: "Lower Back", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Machine"] },

  // FOREARMS (4)
  { id: "forearms-1", name: "Behind the Back Wrist Curl (Barbell)", muscle: "Forearms", muscle_groups: ["Forearms"], category: "Forearms", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "forearms-2", name: "Wrist Curl (Dumbbell)", muscle: "Forearms", muscle_groups: ["Forearms"], category: "Forearms", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "forearms-3", name: "Reverse Wrist Curl (Dumbbell)", muscle: "Forearms", muscle_groups: ["Forearms"], category: "Forearms", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "forearms-4", name: "Farmer's Carry / Grip Hold", muscle: "Forearms", muscle_groups: ["Forearms", "Core", "Traps"], category: "Forearms", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Dumbbell"] },

  // ABDOMINALS (17)
  { id: "abs-1", name: "Front Lever Raise", muscle: "Abdominals", muscle_groups: ["Core", "Lats", "Shoulders"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar"] },
  { id: "abs-2", name: "Heel Taps", muscle: "Abdominals", muscle_groups: ["Core", "Obliques"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-3", name: "Sit Ups", muscle: "Abdominals", muscle_groups: ["Core"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-4", name: "Russian Twist (Weighted)", muscle: "Abdominals", muscle_groups: ["Core", "Obliques"], category: "Abdominals", equipment: "Weight Plate", equipment_list: ["Weight Plate"] },
  { id: "abs-5", name: "Russian Twist (Bodyweight)", muscle: "Abdominals", muscle_groups: ["Core", "Obliques"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-6", name: "Hollow Rock Hold", muscle: "Abdominals", muscle_groups: ["Core"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-7", name: "Single Leg Hip Thrust", muscle: "Abdominals", muscle_groups: ["Glutes", "Hamstrings", "Core"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-8", name: "Knee Raise Parallel Bars", muscle: "Abdominals", muscle_groups: ["Core"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Parallel Bars"] },
  { id: "abs-9", name: "Flutter Kicks", muscle: "Abdominals", muscle_groups: ["Core", "Hip Flexors"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-10", name: "Lying Knee Raise", muscle: "Abdominals", muscle_groups: ["Core"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-11", name: "Crunch", muscle: "Abdominals", muscle_groups: ["Core"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-12", name: "Plank", muscle: "Abdominals", muscle_groups: ["Core", "Shoulders"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-13", name: "Bicycle Crunch", muscle: "Abdominals", muscle_groups: ["Core", "Obliques"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-14", name: "Leg Raise (Hanging)", muscle: "Abdominals", muscle_groups: ["Core", "Hip Flexors"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar"] },
  { id: "abs-15", name: "Cable Crunch", muscle: "Abdominals", muscle_groups: ["Core"], category: "Abdominals", equipment: "Machine", equipment_list: ["Machine", "Cables"] },
  { id: "abs-16", name: "V-Up / Jackknife Sit Up", muscle: "Abdominals", muscle_groups: ["Core"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "abs-17", name: "Ab Wheel Rollout", muscle: "Abdominals", muscle_groups: ["Core", "Shoulders"], category: "Abdominals", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Ab Wheel"] },

  // QUADRICEPS (20)
  { id: "quads-1", name: "Sumo Deadlift", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Hamstrings", "Lower Back"], category: "Quadriceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "quads-2", name: "Kettlebell Goblet Squat", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Core"], category: "Quadriceps", equipment: "Kettlebell", equipment_list: ["Kettlebell"] },
  { id: "quads-3", name: "Sumo Squat (Barbell)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Adductors"], category: "Quadriceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "quads-4", name: "Reverse Lunge", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Hamstrings"], category: "Quadriceps", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "quads-5", name: "Split Squat (Dumbbell)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Hamstrings"], category: "Quadriceps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "quads-6", name: "Lunge (Barbell)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Hamstrings"], category: "Quadriceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "quads-7", name: "Lunge (Dumbbell)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Hamstrings"], category: "Quadriceps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "quads-8", name: "Sissy Squat", muscle: "Quadriceps", muscle_groups: ["Quadriceps"], category: "Quadriceps", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "quads-9", name: "Goblet Squat", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Core"], category: "Quadriceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "quads-10", name: "Lateral Squat", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Adductors"], category: "Quadriceps", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "quads-11", name: "Jump Squat", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes"], category: "Quadriceps", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "quads-12", name: "Back Squat (Barbell)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Hamstrings", "Lower Back"], category: "Quadriceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "quads-13", name: "Front Squat (Barbell)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Core", "Upper Back"], category: "Quadriceps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "quads-14", name: "Leg Press (Machine)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Hamstrings"], category: "Quadriceps", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "quads-15", name: "Leg Extension (Machine)", muscle: "Quadriceps", muscle_groups: ["Quadriceps"], category: "Quadriceps", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "quads-16", name: "Bulgarian Split Squat (Barbell)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Hamstrings"], category: "Quadriceps", equipment: "Barbell", equipment_list: ["Barbell", "Bench"] },
  { id: "quads-17", name: "Bulgarian Split Squat (Dumbbell)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Hamstrings"], category: "Quadriceps", equipment: "Dumbbell", equipment_list: ["Dumbbell", "Bench"] },
  { id: "quads-18", name: "Box Jump", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes"], category: "Quadriceps", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Box"] },
  { id: "quads-19", name: "Pistol Squat", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes", "Core"], category: "Quadriceps", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "quads-20", name: "Hack Squat (Machine)", muscle: "Quadriceps", muscle_groups: ["Quadriceps", "Glutes"], category: "Quadriceps", equipment: "Machine", equipment_list: ["Machine"] },

  // HAMSTRINGS (11)
  { id: "hams-1", name: "Stiff / Straight Leg Deadlift", muscle: "Hamstrings", muscle_groups: ["Hamstrings", "Glutes", "Lower Back"], category: "Hamstrings", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "hams-2", name: "Deadlift (Dumbbell)", muscle: "Hamstrings", muscle_groups: ["Hamstrings", "Glutes", "Lower Back", "Forearms"], category: "Hamstrings", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "hams-3", name: "Single Leg Romanian Deadlift (Dumbbell)", muscle: "Hamstrings", muscle_groups: ["Hamstrings", "Glutes", "Core"], category: "Hamstrings", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "hams-4", name: "Standing Leg Curls", muscle: "Hamstrings", muscle_groups: ["Hamstrings"], category: "Hamstrings", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "hams-5", name: "Deadlift (Band)", muscle: "Hamstrings", muscle_groups: ["Hamstrings", "Glutes", "Lower Back"], category: "Hamstrings", equipment: "Resistance Band", equipment_list: ["Resistance Band"] },
  { id: "hams-6", name: "Glute Ham Raise", muscle: "Hamstrings", muscle_groups: ["Hamstrings", "Glutes", "Lower Back"], category: "Hamstrings", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "hams-7", name: "Good Morning (Barbell)", muscle: "Hamstrings", muscle_groups: ["Hamstrings", "Lower Back", "Glutes"], category: "Hamstrings", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "hams-8", name: "Romanian Deadlift (Barbell)", muscle: "Hamstrings", muscle_groups: ["Hamstrings", "Glutes", "Lower Back"], category: "Hamstrings", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "hams-9", name: "Lying Leg Curl (Machine)", muscle: "Hamstrings", muscle_groups: ["Hamstrings"], category: "Hamstrings", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "hams-10", name: "Seated Leg Curl (Machine)", muscle: "Hamstrings", muscle_groups: ["Hamstrings"], category: "Hamstrings", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "hams-11", name: "Nordic Hamstring Curl", muscle: "Hamstrings", muscle_groups: ["Hamstrings"], category: "Hamstrings", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },

  // GLUTES (10)
  { id: "glutes-1", name: "Lateral Leg Raises", muscle: "Glutes", muscle_groups: ["Glutes", "Abductors"], category: "Glutes", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "glutes-2", name: "Glute Kickback on Floor", muscle: "Glutes", muscle_groups: ["Glutes"], category: "Glutes", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "glutes-3", name: "Single Leg Glute Bridge", muscle: "Glutes", muscle_groups: ["Glutes", "Hamstrings"], category: "Glutes", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "glutes-4", name: "Hip Thrust (Bodyweight)", muscle: "Glutes", muscle_groups: ["Glutes", "Hamstrings"], category: "Glutes", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "glutes-5", name: "Glute Bridge", muscle: "Glutes", muscle_groups: ["Glutes", "Hamstrings"], category: "Glutes", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "glutes-6", name: "Fire Hydrants", muscle: "Glutes", muscle_groups: ["Glutes", "Abductors"], category: "Glutes", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "glutes-7", name: "Hip Thrust (Barbell)", muscle: "Glutes", muscle_groups: ["Glutes", "Hamstrings"], category: "Glutes", equipment: "Barbell", equipment_list: ["Barbell", "Bench"] },
  { id: "glutes-8", name: "Cable Glute Kickback", muscle: "Glutes", muscle_groups: ["Glutes"], category: "Glutes", equipment: "Machine", equipment_list: ["Machine", "Cables"] },
  { id: "glutes-9", name: "Glute Bridge (Resistance Band)", muscle: "Glutes", muscle_groups: ["Glutes", "Hamstrings"], category: "Glutes", equipment: "Resistance Band", equipment_list: ["Resistance Band"] },
  { id: "glutes-10", name: "Donkey Kicks", muscle: "Glutes", muscle_groups: ["Glutes"], category: "Glutes", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },

  // TRAPS (5)
  { id: "traps-1", name: "Shrug (Barbell)", muscle: "Traps", muscle_groups: ["Traps", "Forearms"], category: "Traps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "traps-2", name: "Upright Row (Barbell)", muscle: "Traps", muscle_groups: ["Traps", "Shoulders"], category: "Traps", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "traps-3", name: "Shrug (Dumbbell)", muscle: "Traps", muscle_groups: ["Traps", "Forearms"], category: "Traps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "traps-4", name: "Shrug (Machine)", muscle: "Traps", muscle_groups: ["Traps"], category: "Traps", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "traps-5", name: "Upright Row (Dumbbell)", muscle: "Traps", muscle_groups: ["Traps", "Shoulders"], category: "Traps", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },

  // CALVES (8)
  { id: "calves-1", name: "Calf Raise (Bodyweight)", muscle: "Calves", muscle_groups: ["Calves"], category: "Calves", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "calves-2", name: "Calf Raise (Barbell)", muscle: "Calves", muscle_groups: ["Calves"], category: "Calves", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "calves-3", name: "Calf Raise (Dumbbell)", muscle: "Calves", muscle_groups: ["Calves"], category: "Calves", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "calves-4", name: "Seated Calf Raise (Machine)", muscle: "Calves", muscle_groups: ["Calves"], category: "Calves", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "calves-5", name: "Standing Calf Raise (Machine)", muscle: "Calves", muscle_groups: ["Calves"], category: "Calves", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "calves-6", name: "Leg Press Calf Raise", muscle: "Calves", muscle_groups: ["Calves"], category: "Calves", equipment: "Machine", equipment_list: ["Machine"] },
  { id: "calves-7", name: "Single-Leg Calf Raise", muscle: "Calves", muscle_groups: ["Calves"], category: "Calves", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "calves-8", name: "Jump Rope", muscle: "Calves", muscle_groups: ["Calves", "Cardio"], category: "Calves", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Jump Rope"] },

  // FULL BODY / OLYMPIC (17)
  { id: "fullbody-1", name: "Clean and Jerk", muscle: "Full Body", muscle_groups: ["Full Body", "Shoulders", "Legs", "Back"], category: "Full Body", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "fullbody-2", name: "Overhead Squat", muscle: "Full Body", muscle_groups: ["Legs", "Shoulders", "Core"], category: "Full Body", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "fullbody-3", name: "Farmer's Walk", muscle: "Full Body", muscle_groups: ["Forearms", "Traps", "Core"], category: "Full Body", equipment: "Dumbbell", equipment_list: ["Dumbbell"] },
  { id: "fullbody-4", name: "One-Arm Push-Up", muscle: "Full Body", muscle_groups: ["Chest", "Triceps", "Core"], category: "Full Body", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "fullbody-5", name: "Frog Jumps", muscle: "Full Body", muscle_groups: ["Legs", "Cardio"], category: "Full Body", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "fullbody-6", name: "Muscle Up", muscle: "Full Body", muscle_groups: ["Lats", "Upper Back", "Chest", "Triceps"], category: "Full Body", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Pull Up Bar", "Rings"] },
  { id: "fullbody-7", name: "Clean Pull", muscle: "Full Body", muscle_groups: ["Legs", "Back", "Traps"], category: "Full Body", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "fullbody-8", name: "Hang Snatch", muscle: "Full Body", muscle_groups: ["Full Body", "Shoulders", "Legs"], category: "Full Body", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "fullbody-9", name: "Power Clean", muscle: "Full Body", muscle_groups: ["Full Body", "Legs", "Back"], category: "Full Body", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "fullbody-10", name: "Snatch (Barbell)", muscle: "Full Body", muscle_groups: ["Full Body", "Shoulders", "Legs"], category: "Full Body", equipment: "Barbell", equipment_list: ["Barbell"] },
  { id: "fullbody-11", name: "Kettlebell Swing", muscle: "Full Body", muscle_groups: ["Hamstrings", "Glutes", "Lower Back", "Core"], category: "Full Body", equipment: "Kettlebell", equipment_list: ["Kettlebell"] },
  { id: "fullbody-12", name: "Kettlebell Clean", muscle: "Full Body", muscle_groups: ["Full Body", "Legs", "Shoulders"], category: "Full Body", equipment: "Kettlebell", equipment_list: ["Kettlebell"] },
  { id: "fullbody-13", name: "Kettlebell Snatch", muscle: "Full Body", muscle_groups: ["Full Body", "Shoulders", "Legs"], category: "Full Body", equipment: "Kettlebell", equipment_list: ["Kettlebell"] },
  { id: "fullbody-14", name: "Burpee", muscle: "Full Body", muscle_groups: ["Full Body", "Cardio"], category: "Full Body", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "fullbody-15", name: "Box Jump", muscle: "Full Body", muscle_groups: ["Legs", "Cardio"], category: "Full Body", equipment: "Bodyweight", equipment_list: ["Bodyweight", "Box"] },
  { id: "fullbody-16", name: "Bear Crawl", muscle: "Full Body", muscle_groups: ["Full Body", "Core", "Shoulders"], category: "Full Body", equipment: "Bodyweight", equipment_list: ["Bodyweight"] },
  { id: "fullbody-17", name: "Thruster (Barbell)", muscle: "Full Body", muscle_groups: ["Legs", "Shoulders", "Triceps"], category: "Full Body", equipment: "Barbell", equipment_list: ["Barbell"] }
];

